project_id = "pehloxvqspftiorugkku"

[functions.process-document]
verify_jwt = false

[functions.rag-query]
verify_jwt = false

[functions.extract-pdf-text]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.ingest]
verify_jwt = false